

server:
  port: 8080
  servlet.context-path: /v0.1

spring:
  profiles.active:
  - zero-default
  - zero-local
  #- zero-test
  #- zero-real
  
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  datasource:
    hikari:
      #jdbc-url: jdbc:h2:mem:testdb
      jdbc-url: jdbc:h2:tcp://localhost:9092/kangdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate.ddl-auto: update
    hibernate.ddl-auto: create
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  devtools:
    livereload.enabled: true

# spring.jpa.properties.hibernate.jdbc.time_zone: UTC+9     # can do the feel
# spring.jpa.properties.hibernate.jdbc.time_zone: GMT+9        # unabled to apply
# spring.jpa.properties.hibernate.jdbc.time_zone: Asia/Seoul     # unabled to apply

logging:
  file:
    path: logs/
    max-size: 10MB
  pattern:
    console: "%clr(%d{HH:mm:ss} %-5level){magenta} - %m%n"
    file: "%d %-5level [%-10thread] [%-30logger{30}] - %m%n"
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.thymeleaf: info
    org.h2.server.web: info



# --------------------------------------------------------
---
spring.profiles: zero-default

project:
  name: zero
  author: Kiea Seok Kang
  
file:
  from:
    board: src/main/resources/txt/board.txt
    word:  src/main/resources/txt/org_word2500.txt
    chun:  src/main/resources/txt/org_1000.txt
    mid:   src/main/resources/txt/org_mid.txt
  to:
    board:     src/main/resources/json/board.json     # board
    word:      src/main/resources/json/word.json      # word
    chun:      src/main/resources/json/chun.json      # chun
    grp:       src/main/resources/json/grp.json
    sent:      src/main/resources/json/sent.json
    tip:       src/main/resources/json/tip.json
    mid:       src/main/resources/json/mid.json       # mid
    division:  src/main/resources/json/division.json
    comp:      src/main/resources/json/comp.json


# --------------------------------------------------------
---
spring.profiles: zero-local

# --------------------------------------------------------
---
spring.profiles: zero-test

# --------------------------------------------------------
---
spring.profiles: zero-real


